### ISSUE TITLE
Long running cluster list view affects overall performance of browser

### ISSUE THREAD

**Issue by pkprzekwas** [kubermatic/dashboard#5969] opened 2023-05-16 10:37 UTC
### What happened

After leaving application on the cluster list view in a separate browser tab for a while (several hours), my browser performance degraded.

### Expected behaviour

Browser should freeze the unused tab to avoid affecting its overall performance.

### Environment
- UI Version: 2.22+
- API Version: 2.22+
- Domain: dev.kubermatic.io
- Others:
I had my development console opened on the side which might have disable browser from freezing the process.
The browser I was using was Brave (Version 1.51.110 Chromium: 113.0.5672.77 (Official Build) (arm64))

**Comment by ahmedwaleedmalik** [comment] 2023-06-13 09:04
Closing this since no information was provided for this ticket leaving us with no way to reproduce this 🤷‍♂️

**Closed by ahmedwaleedmalik** 2023-06-13 09:04 UTC
Labels: kind/bug, triage/needs-information, sig/ui

**Comment by pkprzekwas** [comment] 2023-06-13 10:08
Sorry, I got swamped and totally forgot about this issue. If I find some time, I'll try to reproduce, leave appropriate instructions and reopen this issue. There is a big chance I had my browser's debug console opened at that time.

**Comment by pkprzekwas** [comment] 2023-07-31 15:16
I did some testing and it seems that the issue appears only when I keep my network tab opened for a long time, meaning that is shouldn't affect our end users.
