### ISSUE TITLE
vSphere credentials split is unclear and needs better description

### ISSUE THREAD

**Issue by embik** [kubermatic/dashboard#5952] opened 2023-05-11 07:15 UTC
**What is the problem, where is it and why is it an issue?**

The step in the cluster creation wizard that asks for cloud provider settings (mostly credentials) for vSphere is super confusing to people not familiar with the implementation details. I had to look at the dashboard code to actually understand what was being set.

In the vSphere provider implementation, you can pass dedicated credentials for "general usage" (which effectively means CCM/CSI) and for infrastructure management (mostly resource provisioning in KKP and machine-controller).

![Screenshot 2023-05-11 at 09 14 42](https://github.com/kubermatic/dashboard/assets/10295525/79f02164-bcef-420a-992c-7f0f01f9fc6a)

The problem in specific is that it's unclear what the "Use custom VSphere Cloud credentials" checkbox does. When I hear "cloud credentials" (knowing that we have "infrastructure management" credentials), I think those credentials are used to provision cloud resources. However, they are actually the CCM / CSI credentials. Nothing in the wizard step indicates this. 

The wizard behaves very different from the `Cluster` CRD, because there the _infrastructure management credentials_ are optional, not the CCM/CSI credentials. This adds to the confusion for someone knowing the CRD definitions.

**Suggest how to fix it, if possible**

Multiple options:

1. Switch things around and make the optional credentials the "infrastructure management" credentials, which means changing the label on the checkbox to e.g. "Use dedicated credentials to provision vSphere resources".
2. Clarify the existing label, either by changing it to e.g. "Use custom credentials for vSphere CCM and CSI" or by adding an info box to the checkbox that gives details on how the credentials are being used.

**Comment by Waseem826** [comment] 2023-05-11 08:55
This looks like a duplicate of https://github.com/kubermatic/dashboard/issues/3004 but since this ticket has better description I guess we can close the older one.

**Comment by embik** [comment] 2023-05-11 08:57
I should have looked for duplicates before creating this, my bad @Waseem826 - thanks for spotting it.

**Comment by ahmedwaleedmalik** [comment] 2023-05-11 15:15
As per the discussion in sig-api-ui, https://github.com/kubermatic/dashboard/pull/5956 doesn't close this issue:

`No, because the new label says the optional credentials are used for infrastructure, when in fact they are used for CCM/CSI` 

Hence, we need to work on this again.

**Comment by embik** [comment] 2023-05-11 15:15
Reopened because #5956 put the wrong label on the checkbox. It actually needs to advertise that the optional credentials are used for CCM/CSI with the current implementation.

**Closed** 2023-05-15 06:17 UTC
Labels: kind/design, sig/ui
