### ISSUE TITLE
Display node size name instead of value in wizard summary

### ISSUE THREAD

**Issue by j3ank** [kubermatic/dashboard#79] opened 2017-07-24 09:08 UTC
display node Size name instead of value

**Comment by maciaszczykm** [comment] 2020-08-19 09:01
Let's take another look.

**Comment by maciaszczykm** [comment] 2020-08-19 10:25
The problem is the same in the new wizard. We would have to implement some kind of workaround (i.e. service with cache that will store the size display name) or do some bigger changes (i.e. use not only size name but whole structure with other details).

As @floreks correctly pointed out the most important place to show more details (i.e. memory, CPU or price) is the place where user selects the node size, so node settings view, and there we display more information.

I will close the issue but feel free to reopen if you would rather have it done.

**Closed by maciaszczykm** 2020-08-19 10:25 UTC
Labels: kind/cleanup, lifecycle/blocked, priority/low, team/ui
