### ISSUE TITLE
Test Live Quota - Release 2.22

### ISSUE THREAD

**Issue by KhizerRehan** [kubermatic/dashboard#5584] opened 2023-01-24 09:10 UTC
## Testing Procedure user story

**Testing live quota**

**Pre-Requisites:**

- Live quota works for any **project** which have quotas configured.

#####  How to configure quota for any project?
- Make sure you are an admin.
- Navigate to Project Quotas section from admin section
- Set Quota for a Project via dialog.

### Live Quota General Testing:

- [x] Make sure Quotas are configured for a project and it should display configured quotas to following places.
	- [x] Project Overview page progress bars should be visible under the heading of "Project Quota"
	- [x] Create Cluster From Template dialog should show configured quota
	- [x] Cluster list page should show configured quota
	- [x] Cluster Details page should show configured quota
	- [x] MD dialog should show configured quota

### Testing Live Quota 

**+ve Case**
- Try to create cluster via wizard
- Navigate to Initial Nodes step

**In case cluster exists already**
- [x] Check cpu, memory, storage shows **used** quota if cluster is already created
- [x] It should show multiple colors differentiating used + buffer allowed.
e.g
<img width="626" alt="multiple-colors" src="https://user-images.githubusercontent.com/17727069/214580519-253f096b-b3ad-4d24-8dd3-b0990e82b6de.png">

- [x] If user exceeds the allowed quota 
     - [x] it should show error message "The estimated quota will exceed project quota. "
    - [x] a Quota Exceeded warning should appear beside the `next` and `back` buttons 
    - [x] user won't be allowed to create a cluster in the last step of the wizard the `create cluster` button will be disabled but you can create a cluster template.

**In case "new" cluster creating*
- [x] It should show light blue color to show buffer value how much user is allowed to create cluster.

<img width="661" alt="quota-cration" src="https://user-images.githubusercontent.com/17727069/214581240-4281cf88-2934-4548-917d-5f7d178a3463.png">

- [x] If user exceeds the allowed quota 
    - [x] it should show error message "The estimated quota will exceed project quota. "
    - [x] a Quota Exceeded warning should appear beside the `next` and `back` buttons 
    - [x] user won't be allowed to create a cluster in the last step of the wizard the `create cluster` button will be disabled but you can create a cluster template.

#### Add MD (Details Page)
- [x] On new MD addition Quota widget should update widget bars to validate if new resources is allowed to create with in project resource quota otherwise creation of resource should be blocked.
- [x] Exceeding quota shouldn't allow user to "Add Machine Deployment"
	- [x] it should show error message "The estimated quota will exceed project quota. "

#### Edit MD [Fix resource quota calculation for Edit MD](https://github.com/kubermatic/dashboard/pull/5646) (Details Page)
- [x] Live quota should work based on provider specific model
- [x] Increased in Replica Count, Disksize or Provider specific e.g AWS -> Node Size should trigger quota calculation
- [x] Exceeding quota shouldn't allow user to "Save Changes"
	- [x] it should show error message "The estimated quota will exceed project quota."

## Live quota for Cluster Templates
**Notes: for tester** : Cluster Creation via Templates is allowed it **won't** prevent to create cluster even though if it exceeds
- [x] If user exceeds the allowed quota the cluster will be created via Dialog without any customization.
- [x] It should show warning icon even if cluster is created and widget should apprehend and show details accoridingly (This Feature will be done on next release)
<img width="332" alt="warnign" src="https://user-images.githubusercontent.com/17727069/214582453-3117ff31-5fd1-4904-b9cd-52c7cfbb10f8.png">

- [x] If user tries to create cluster via wizard by **customizing** cluster template user shouldn't be allowed to create cluster since it is **already exceeding** quota wizard

## Acceptance Criteria
- [x] Quotas should be configured properly to project.
- [x] Prevent Creation Of Resources if Quota is Hit **(Cluster creation via wizard)**
- [x] Prevent Creation Of Resources if Quota is Hit **(MD creation)**
- [x] Prevent Creation Of Resources if Quota is via **(Customizing Cluster Template)**
- [x] Allowed Creation Of Resources **even** if quota is hit via **(Cluster Template Dialog)** 
- [x] Quota Calculation API request should be sent when application is running in Community Edition

If quota is hit (at 100%) or overdrawn disable the following buttons a
	- [ ] Create Cluster 
	- [ ] Add Machine Deployment

**Important note !!** 

Live quota **doesn't** cater Cluster Templates **Dialog** view as it requires backend changes since we only have `clusterTemplateID` and replica count in order to upgrade quota based on what compute size is defined in template should be figured by backend + No of Clusters.

However **Preventing* creation of resources should work for 
- Customising Cluster
- Normal Cluster wizard

Allows option to "Save Template and Create" or "Save Template" so **No** widget is displayed
- Add Cluster Template ( Save Template and Opens Same dialog as Dialog) becomes same as above
"_Live quota **doesn't** cater Cluster Templates **Dialog** _"

Allows option to save Template or create new one so **No** widget is displayed
- Edit Cluster Template

### Other Features
- [x] Check the API documentation

**Comment by ahmadhamzh** [comment] 2023-01-26 10:09
in case create or edit or customize cluster template, i think we need to not block the user on the initial node step if the quota is exceeded, because the user might not want to create a cluster he might want just to create new cluster template so we need in case of quota exceeded to only disable the buttons for creating new cluster 

so regarding wizard for cluster template we have three options, in all of them we need to let the user to go through all of the wizard steps: 

1- create cluster template :
`save template and create cluster` button will be disable  |  `save cluster template` button will stay enable

2- customize cluster template :
`save as new template` button will stay enable ||  `create cluster from customized template` button will be disable 

3- edit cluster template :
`save as new template` & `save changes to template` buttons will stay enable

**Comment by ahmadhamzh** [comment] 2023-01-26 10:13
so in the pic below im trying to increase the replica from 1 to 2 in the quota calculation that suppose to mean add one replica, but what happend is that in the quota it's show as im adding two replica ( i.e. the quota calculation is acting like im adding MD not Editing MD) 

im not sure if it's related to backend or frontend @lsviben @KhizerRehan 

![image.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/0839e3df-179d-43fd-a305-ed2462413e40)

![image.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/a75f0565-6eef-4866-a389-ab763dc026de)

**Comment by lsviben** [comment] 2023-01-26 10:36
So, the API is stupid in this case, it just calculates based on the replicas given in the request. The amount of replicas in the request should be the amount of new replicas. So in this case, if 1 is already there, and you are adding 1 more, the request should have 1.

this is because the API just takes the current quota and adds what is in the request.

So @KhizerRehan , do you think you could handle this from the UI side?

**Comment by KhizerRehan** [comment] 2023-01-26 12:23
> in case create or edit or customize cluster template, i think we need to not block the user on the initial node step if the quota is exceeded, because the user might not want to create a cluster he might want just to create new cluster template so we need in case of quota exceeded to only disable the buttons for creating new cluster
> 
> so regarding wizard for cluster template we have three options, in all of them we need to let the user to go through all of the wizard steps:
> 
> 1- create cluster template : `save template and create cluster` button will be disable || `save cluster template` button will stay enable
> 
> 2- customize cluster template : `save as new template` button will stay enable || `create cluster from customized template` button will be disable
> 
> 3- edit cluster template : `save as new template` & `save changes to template` buttons will stay enable

Agreed on this point

**Comment by KhizerRehan** [comment] 2023-01-26 12:26
> So, the API is stupid in this case, it just calculates based on the replicas given in the request. The amount of replicas in the request should be the amount of new replicas. So in this case, if 1 is already there, and you are adding 1 more, the request should have 1.
> 
> this is because the API just takes the current quota and adds what is in the request.
> 
> So @KhizerRehan , do you think you could handle this from the UI side?

As per discussion it was doable from UI side if only replica count was changed but on Edit case we have an option to change provider specific options e.g AWS -> Node Size can be changed.

So basically, changing Node Size  + Replica Count **BOTH** from dialog backend should have to do Recalculation and returns new estimated quota.

We can't just decrease replica count by HOW many times it is changed from Prev to New value the estimation calculation will be wrong IMHO as what i have understood. So therefore it will be fixed from backend.

**Comment by KhizerRehan** [comment] 2023-02-07 09:26
Hi, @ahmadhamzh  description of ticket is slightly updated specifically for `Live quota for MD` heading you need to test for (Add/Edit) MD there is slightly technically difference from code POV but as the tester for this ticket functionality should work and please test this Add/Edit for random providers e.g

- Kubevirt, Hetzner  random picking providers just to confirm there might not be bug if something is not catered.

**Comment by Waseem826** [comment] 2023-02-07 11:48
Quota calculation API for KubeVirt returns following error in Edit MD dialog:
```
{
    "code": 400,
    "message": "invalid request, failed getting resources from request body: failed to parse kubevirt node storage \"10GiG\" to resource quantity: unable to parse quantity's suffix"
}
```

Payload:

```
{
    "replicas": 1,
    "kubevirtNodeSize": {
        "primaryDiskSize": "10G",
        "cpus": "2",
        "memory": "2048M"
    },
    "replacedResources": {
        "replicas": 1,
        "kubevirtNodeSize": {
            "primaryDiskSize": "10GiG",
            "cpus": "2",
            "memory": "2048M"
        }
    }
}
```

**Comment by ahmadhamzh** [comment] 2023-02-08 06:52
in azure i think something wrong with the node size that effect the quota to be exceeded 
this is the sizes come from backend :
![Screenshot from 2023-02-08 09-35-53.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/e5d56c84-1ed1-4e2c-9a58-d3819d447538)

and this is the payload from quota calculation :
![image.png](https://images.zenhubusercontent.com/620cc25fdd7f2fda29272d20/50faed81-fc4a-41f2-b047-a55fa865a10c)
 so the issue is with `osDiskSizeInMB` im not sure do we need to send it in the payload and i think the value that come from backend is wrong

**Comment by KhizerRehan** [comment] 2023-02-08 07:15
@ahmadhamzh you can ask @pkprzekwas for this thing just make sure UI is passing correct payload which i guess it is as Node size is returning from backend and we just filter from dropdown and pass to backend for quota calculation

**Comment by KhizerRehan** [comment] 2023-02-08 07:16
> Quota calculation API for KubeVirt returns following error in Edit MD dialog:
> 
> ```
> {
>     "code": 400,
>     "message": "invalid request, failed getting resources from request body: failed to parse kubevirt node storage \"10GiG\" to resource quantity: unable to parse quantity's suffix"
> }
> ```
> 
> Payload:
> 
> ```
> {
>     "replicas": 1,
>     "kubevirtNodeSize": {
>         "primaryDiskSize": "10G",
>         "cpus": "2",
>         "memory": "2048M"
>     },
>     "replacedResources": {
>         "replicas": 1,
>         "kubevirtNodeSize": {
>             "primaryDiskSize": "10GiG",
>             "cpus": "2",
>             "memory": "2048M"
>         }
>     }
> }
> ```

Strange i can check it again if it's issue from UI side because i think parsing due to `GiG` need to investigate this issue

**Comment by ahmadhamzh** [comment] 2023-02-09 08:27
all seems good

**Comment by Waseem826** [comment] 2023-02-09 11:29
I noticed that if we save KubeVirt cluster template which has `Instance Type` and `Preference` values, then editing/customizing that template causes following API error for quota calculation:

```
{
    "code": 400,
    "message": "invalid request, failed getting resources from request body: error converting kubevirt node size cpus \"undefined\" to int: strconv.Atoi: parsing \"undefined\": invalid syntax"
}
```

Request payload:
```
{
    "replicas": 1,
    "kubevirtNodeSize": {
        "primaryDiskSize": "20",
        "cpus": "undefined"
    }
}
```

**Comment by ahmadhamzh** [comment] 2023-02-16 16:00
all seems good there is only one issue will be fixed in : https://github.com/kubermatic/dashboard/pull/5751

**Closed** 2023-02-16 16:00 UTC
Labels: testing, sig/ui
