### ISSUE TITLE
UI session expires even if user is active

### ISSUE THREAD

**Issue by chrkl** [kubermatic/dashboard#1833] opened 2019-11-28 15:20 UTC
**User Story**

The UI session expires after a fixed timespan, regardless of the users activity. This might cause a user to be logged out while interacting with the UI. The user should rather be logged out after an idle period or the session be renewed as long as the user is active.

**Acceptance criteria**

The session should be kept alive as long as user activity is given.

**Comment by maciaszczykm** [comment] 2020-07-15 13:30
This seems to be a duplicate of https://github.com/kubermatic/dashboard/issues/1108.

**Closed by maciaszczykm** 2020-07-15 13:30 UTC
Labels: blocked by backend, priority/normal, team/ui
